### ISSUE TITLE
React Typist does not work with Vite ? [solved]

### ISSUE THREAD

**Issue by YidirK** [jstejada/react-typist#129]
I use **Vite** , **react js** , **material-tailwind** and **talwind**, at first I thought that the problem comes from `<typographie>` of material-tailwind , but I use another normal text tag, and it still does not work while I think it comes from **Vite**

**Input :**
```
  <div className="absolute top-0 left-0 w-full h-screen flex items-center justify-center">
    <Typography color="white" variant="h1"><Typist>We build the future that you deserve.</Typist></Typography>
      </div>
```

**Output :**
![image](https://github.com/jstejada/react-typist/assets/31509703/f625d89c-9aee-41d9-8c66-385600b7b48d)

**Comment by vadym-kovryzhkin** [comment]
this is not about Vite, but about strict mode. Go to the main.tsx and remove <React.StrictMode>

**Comment by YidirK** [comment]
@vadym-kovryzhkin 
Thank you, I deleted `<React.StrictMode>` and it's working. Thank you for the answer  <3
