### ISSUE TITLE
Depending on the sentence or padding the animation stops at random places, no matter the length of text

### ISSUE THREAD

**Issue by tmpg** [jstejada/react-typist#13]
Depending on the sentence or padding the animation stops at random places, no matter the length of the passage. If I change the word or spacing I can get it to complete but this means that it can not just take any text without review.

Has anyone else run into this issue? Any workarounds?

Thanks,
Tim

**Comment by tmpg** [comment]
solved this by using padding instead of margins.

**Comment by tmpg** [comment]
Never mind it still happens but less frequent...

**Comment by tmpg** [comment]
I "solved" my issue by adding "whitespace: pre-wrap" onto the element but it causes a nasty stutter in the typing. Let me know if I could be of any help when you get to fixing this.

**Comment by jstejada** [comment]
this seems related to #15.

**Comment by jstejada** [comment]
The fix for this has been released with v1.1.0. Let me know if you continue having issues!

**Comment by ahcarpenter** [comment]
@jstejada Noticed it with 1.1.1. Seems to work when using 'Helvetica', but not 'Open Sans' for some reason--any thoughts?

**Comment by jstejada** [comment]
I'll have to take another look!
