### ISSUE TITLE
How to include the 'dist/Typist.css'

### ISSUE THREAD

**Issue by FanXiang** [jstejada/react-typist#16]
How to include the 'dist/Typist.css' on Dev and Production

**Comment by jch254** [comment]
@FanXiang if you're using Webpack make sure to load the CSS files from node_modules/react-typist and then `import 'react-typist/dist/Typist.css';` before using the component

**Comment by jstejada** [comment]
@FanXiang that is correct. It really depends on your build process, in some cases just adding a `<link>` tag
