### ISSUE TITLE
Internet Explorer 11 support

### ISSUE THREAD

**Issue by ulich** [jstejada/react-typist#23]
What are the supported browsers? Could this information be added to the Readme maybe?

I am seeing issues with IE11. You are using the static array methods that are not supported by IE11. Any plans on supporting IE11?

**Comment by dan-clark-lm** [comment]
+1 IE support would be great...

**Comment by lnxmad** [comment]
Bump

**Comment by jstejada** [comment]
Hey sorry for the delay in getting back here! Replied in #24

**Comment by goldensunliu** [comment]
this is what the error looks like https://github.com/jstejada/react-typist/pull/24#issue-220698292

**Comment by jstejada** [comment]
closing given resolution in #24
