### ISSUE TITLE
Not working properly using dangerouslySetInnerHTML.

### ISSUE THREAD

**Issue by slorenzo** [jstejada/react-typist#34]
Hello.
I'm wanna make a component passing the content as a property.
My code is:  
<img width="468" alt="screen shot 2017-11-10 at 5 49 43 pm" src="https://user-images.githubusercontent.com/15804684/32678055-93d6cca2-c63f-11e7-828f-90c9bb9be0c3.png">

Nothing happens, nothing on the console either.
Is it possible?

Sebastian.

**Comment by lfeddern** [comment]
@slorenzo did you manage to get anywhere with this?

**Comment by slorenzo** [comment]
@lfeddern To my purpose, I used [react-typist-loop](https://github.com/ratson/react-typist-loop).
But it needs to be reviewed,

**Comment by jstejada** [comment]
Hey @slorenzo, unfortunately Typist doesn't support text in `dangerouslySetInnerHTML`, and given how Typist is implemented, I don't think it's feasible to support it.

Typist works based on the `children` element tree you pass to it, but when using `dangerouslySetInnerHTML`, there's no tree, and the prop is just an html string, so there's not a straightforward way of extracting the text.

Why do you need to use `dangerouslySetInnerHTML`?

**Comment by kubijo** [comment]
Hi @jstejada,

I've bumped into this as well when trying to use this with our solution for translations of html strings.
When you need to give your translators strings with line breaks, you need to render them back somehow and the `dangerouslySetInnerHTML` is pretty much an obvious solution.

**Comment by kubijo** [comment]
Although line-breaks in particular can be resolved by including newlines  (`\n`) in the string and giving the wrapping element `white-space: pre-wrap` style…
