### ISSUE TITLE
react element does not render

### ISSUE THREAD

**Issue by lfeddern** [jstejada/react-typist#35]
React element as a child doesn't render, to recreate:

![screen shot 2017-11-24 at 20 45 43](https://user-images.githubusercontent.com/10187990/33223596-d117582e-d158-11e7-9893-f1a86d28124c.png)

Just renders the cursor:
![screen shot 2017-11-24 at 20 49 48](https://user-images.githubusercontent.com/10187990/33223627-19b831f2-d159-11e7-9eb6-4aa3f7ca72be.png)

**Comment by lfeddern** [comment]
think its something to do with `cloneElementWithSpecifiedText()` but can't fix. Any help much appreciated!

**Comment by jstejada** [comment]
@lfeddern sorry for the delay in getting back to you! Unfortunately this use-case is not supported; the way typist works is by traversing the element tree you pass as `children` and rendering any text it finds inside of it. 
however, when you use your own custom defined elements, their render implementation is hidden from the element tree and it's just used by React when actually "resolving"/rendering the virtual DOM to actual DOM.

In your example, the `children` tree looks something like this:

```javascript
{
 type: Test,
 props: {}
}
```

As you can see, `props` is empty, so there's no `children` to keep traversing and no text that's available in the tree. Your `Test` element will actually be rendered to text by React when it's actually rendering the virtual dom to actual dom, but the internals of the element are hidden to the parent.

To make it work, you'd need to do something like the following:
```javascript
<Typist>
  <Test>
    Some text
  </Test>
</Typist>
```

Hope this helps! I'll try to document this more clearly in the readme.  Let me know if you have any questions
