### ISSUE TITLE
The link to the CSS file is gone

### ISSUE THREAD

**Issue by barbush** [jstejada/react-typist#36]
Help a fellow out and put it back? :-)

**Comment by jstejada** [comment]
Ah that was my bad, I stopped commiting the `dist` folder. However, you should be able to find it in the installed package: `node_modules/dist/Typist.css`

If using webpack or a similar setup you should be able to import it from `import 'react-typist/dist/Typist.css'`

Let me know if that helps!

**Comment by barbush** [comment]
Juan, that works - much appreciated!
