### ISSUE TITLE
react-typist@0.3.0   npm WARN EPACKAGEJSON name@1.0.0 No repository field.

### ISSUE THREAD

**Issue by msutyak** [jstejada/react-typist#4]
Using a Meteor.js application.  I installed meteorhacks:npm and the appropriate react packages.  

My packages.json looks like:
`
{
  "name": "name",
  "version": "1.0.0",
  "description": "react",
  "main": "index.js",
  "dependencies": {
    "react-dom": "^0.14.7",
    "react-typewriter": "^0.3.0",
    "react-typist": "^0.3.0"
  },
  "devDependencies": {},
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC"
}
`

I receive this output when I try to install:

`
******:myproject *********$ npm install react-typist --save
name@1.0.0 /Users/***********/www/myproject
└── react-typist@0.3.0 

npm WARN EPACKAGEJSON name@1.0.0 No repository field.
`

What is happening here?

**Comment by jstejada** [comment]
hi @msutyak, I believe this is because your `package.json` does not contain a repository field. This is unrelated to react-typist.

Thanks!
