### ISSUE TITLE
Typist.Backspace and Typist.Delay not working while using react-hot-loader

### ISSUE THREAD

**Issue by vmarchesin** [jstejada/react-typist#45]
**Dependencies:**

```json
"devDependencies": {
    "babel-core": "^6.26.0",
    "babel-loader": "^7.1.4",
    "babel-preset-env": "^1.6.1",
    "babel-preset-react": "^6.24.1",
    "babel-preset-stage-0": "^6.24.1",
    "clean-webpack-plugin": "^0.1.19",
    "css-loader": "^0.28.11",
    "eslint": "^4.19.1",
    "eslint-plugin-react": "^7.7.0",
    "extract-text-webpack-plugin": "^4.0.0-beta.0",
    "file-loader": "^1.1.11",
    "html-webpack-plugin": "^3.2.0",
    "node-sass": "^4.8.3",
    "react-hot-loader": "^4.0.1",
    "sass-loader": "^6.0.7",
    "style-loader": "^0.20.3",
    "webpack": "^4.5.0",
    "webpack-cli": "^2.0.13",
    "webpack-dev-server": "^3.1.1"
  },
  "dependencies": {
    "@fortawesome/fontawesome": "^1.1.5",
    "@fortawesome/fontawesome-free-brands": "^5.0.9",
    "@fortawesome/fontawesome-free-solid": "^5.0.9",
    "@fortawesome/react-fontawesome": "0.0.18",
    "bootstrap": "^4.0.0",
    "classnames": "^2.2.5",
    "react": "^16.3.1",
    "react-dom": "^16.3.1",
    "react-router-dom": "^4.2.2",
    "react-transition-group": "^2.3.0",
    "react-typist": "^2.0.4",
    "reactstrap": "^5.0.0-beta.3",
    "styled-components": "^3.2.5"
  }
```

**Code sample:**
```
<Typist
  cursor={{ element: '_' }}
  startDelay={1000}
>
  Example
  <Typist.Backspace count={3} delay={500} />
</Typist>
```

**Expected Behavior:**
It should write `Example` then backspace to `Exam`.

**Current Behavior**
Doesn't backspace at all. Same thing happens with `Typist.Delay`, doesn't work.

I took a brief look at the code but didn't find the issue.

**Comment by jstejada** [comment]
Hey @vmarchesin that's weird! Do you see any errors in the console or any additional output that might be helpful?

**Comment by vmarchesin** [comment]
No apparent errors. I tried log debugging and the components exist as functions, so it should work. There's no logs or erros, it just ignores the call. If I place any text after `Typist.Backspace` or `Typist.Delay` components they are printed; the code just ignores backspaces and delays. I _may_ be doing something wrong, but since the main feature works I don't think it's an issue with the package install or syntax. Maybe compatibility?

**Comment by jstejada** [comment]
awesome @vmarchesin, thanks for looking into this! I'll keep it open in case other people run into this issue.

thanks! :)

**Comment by alexhayes** [comment]
I'd say this can be closed down now that #42 has been merged - both backspace and delay work when using react-hot-loader w/ nextjs

**Comment by vmarchesin** [comment]
I will test with webpack and report back

**Comment by jstejada** [comment]
Okay, going to go ahead and close it

**Comment by shezankazi** [comment]
I am using Next.js and backspace does not seem to work. How exactly did OP solve this?

**Comment by alexhayes** [comment]
@shezankazi I believe we're waiting on a new release of react-typist

To get by in the meantime I cloned the repo locally, built it then included the build in my project and imported that.

**Comment by krean93** [comment]
+1 Backspace does not work for me when using next.js.

**Comment by alexhayes** [comment]
@krean93 using the method I outlined above hot reloading did work for me.

**Comment by vmarchesin** [comment]
Using it in production solves the issue. If the current release does not include #42 (commit db0b4c3) it probably won't work in dev with hot-reload.
