### ISSUE TITLE
install from github

### ISSUE THREAD

**Issue by gernotkogler** [jstejada/react-typist#48]
I would like to use the most recent version directly from github. I installed the package using 

npm install jstejada/react-typist#master

The module source is installed but not built and therefore does not work. "import Typist from 'react-typist'" fails.

How am I supposed to handle this?

Thanks!

**Comment by jstejada** [comment]
Hey @gernotkogler, unfortunately the built code isn't hosted on github, oinly the source code. You could manually clone it, build it, and install from a local directory, but you'd have to manually keep it up to date.

Sorry for the trouble!
