### ISSUE TITLE
Add support for backspace animation

### ISSUE THREAD

**Issue by msutyak** [jstejada/react-typist#5]
Also, is there a way to have an infinite loop of typing on the same line (write one line, backspace it, then write another line, backspace it, then loop back to the first line, etc...)

**Comment by jstejada** [comment]
hey @msutyak thanks for asking. Currently Typist doesn't support backspace animations, as the README checklist indicates. I'm open to pull requests though!

**Comment by jstejada** [comment]
see #17

**Comment by jstejada** [comment]
landed in #27! Will be released soon
