### ISSUE TITLE
Cursor is appearing in another line

### ISSUE THREAD

**Issue by pedroapfilho** [jstejada/react-typist#53]
The cursor is appearing on the next line, and not on the current one.

I'll place the code here:

```
<Typist>
    <div className="weather-title">
      <h3>title</h3>
      <div className="p-holder">
        <p>
          another text
        </p>
        <p>
          another text
          </a>?
        </p>
        <p>
          text
        </p>
      </div>
    </div>
  </Typist>
```

**Comment by jmpolitzer** [comment]
@pedroapfilho  Check out issue #15.

**Comment by DevelopwithTom** [comment]
How do you include the dist/Typsit.css?

**Comment by shakeszka** [comment]
I had the same problem with
`<Typist className = "typistText">
  <p>My Personal Telegram Blog</p>
  <Typist.Backspace count={26} delay={1500} />
  <p>My Life in Telegram</p>
</Typist>`

I just put tag "span" instead of "p" and everything started working well :D
