### ISSUE TITLE
Use in GatsbyJS

### ISSUE THREAD

**Issue by byio** [jstejada/react-typist#54]
Hi! I'm trying to use this package in a GatsbyJS project but the Typist component doesn't seem to render. Tested it on a CRA, and it works great!

Has anyone else tried using this on a GatsbyJS project?

**Comment by alexluong** [comment]
Hey @byio, I use react-typist on my Gatsby site. You can check it out at: https://github.com/alexluong/blog/blob/master/src/components/Header/index.js.

I also use it in Gatsby v2 (WIP) on another branch if you're interested.

**Comment by byio** [comment]
Hi @alexluong! Thanks for your help.

I've just started started a gatsby-starter-hello-world project, installed react-typist, imported it into my index.js page, and did:

`<Typist>hello world!</Typist>`

However, nothing renders on the page. I inspected the page and instead, saw:

```
<div class="Typist ">
   <!-- react-text: 10 -->
   <!-- /react-text -->
   <!-- react-empty: 11 -->
</div>
```

I'm not sure if I missed something.

**Comment by alexluong** [comment]
Can you set up a repo for it?

**Comment by byio** [comment]
sure! [](https://github.com/byio/gatsby-test)

**Comment by byio** [comment]
Oh my god! I'm so sorry. I figured it out. It's got something to do with my styles.

**Comment by buxzee** [comment]
Hi @byio @alexluong can you share how you solve this issue. I get below build error:

**_If you're trying to use a package make sure that 'Typist' is installed. If you're trying to use a local file make sure that the path is correct._**

I am importing below two lines inside index.js page

```
import Typist from 'Typist'
import './main.scss'
```

I also tried `import Typist from 'react-typist'` but I get the same above error.

and then inside return function, I have below code:

```
<Typist cursor={{ hideWhenDone: true }}>
  <Typist.Delay ms={500} />
  <TypistContent>Hello World!</TypistContent>
</Typist>
```

Please advise how should I use this package in my gatsby project.
