### ISSUE TITLE
Typist.Delay not working properly

### ISSUE THREAD

**Issue by joaom182** [jstejada/react-typist#56]
Hello, i'm trying to use Typist.Delay but is not working properly, see example above:

![typist](https://user-images.githubusercontent.com/3612098/43752889-77f996f4-99d9-11e8-831b-988c7078a280.gif)

on code has Delay of 9050ms between two lines.

![screen shot 2018-08-07 at 00 31 22](https://user-images.githubusercontent.com/3612098/43752897-820879e4-99d9-11e8-813e-b0737d9becbe.png)

**Comment by huhuanming** [comment]
It's not working on hot-reload mode.

**Comment by jstejada** [comment]
merging into #45
