### ISSUE TITLE
Cursor not Blinking 

### ISSUE THREAD

**Issue by nodeicode** [jstejada/react-typist#74]
``` javascript 
<Typist avgTypingDelay={200}
        startDelay={1000}
        cursor={{blink:true}}
        onTypingDone={this.renderAbout}>
        <a>Hello!</a>
      <Typist.Delay ms={500}/>
      <Typist.Backspace count={6} delay={50}/>
        </Typist>
```
This is inside my React Render function. setting `cursor={{blink:true}}` and my CSS has `cursor: pointer;` still it does not blink?

**Comment by larsfischu** [comment]
There was a CSS file for this (https://github.com/jstejada/react-typist/blob/1a3de27b580e765d310b8f82d46ebef6bec66def/dist/Typist.css)
