### ISSUE TITLE
typist with react@17.0.0

### ISSUE THREAD

**Issue by pnguyen001** [jstejada/react-typist#99]
Can you update to work with react@17.0.0 and react-dom@17.0.0

![image](https://user-images.githubusercontent.com/42821297/110848202-d4572000-827b-11eb-8d18-bb975bc61ca8.png)

**Comment by vishnu-dev** [comment]
@jstejada Can we get some attention on this?

**Comment by mah-moh** [comment]
Try like this `npm install react-typist --save --legacy-peer-deps`. With this `--legacy-peer-deps` flag it overlooks the peer dependencies. Don't know if it is the proper way but it works fine.
